package weatherpony.partial;


public enum WrapTiming{//the use of these timings isn't very rigid. these are the cases i imagine they would be used for.
	Early,//if you don't really care what the parameter or return values are (ie. just care about when it's called, rather than how or why)
	Mid,//if you want to change what the parameters are, or other basic manipulations (such as editing a parameter or return value)
	Late,//for editing parameters given based on other parameters, or the value returned based on given and/or passed parameters. The parameters might technically be modified after your hook is initially called
	@Deprecated
	Replacement,//higher-level manipulations such as method replacement. this is here to avoid too bad of issues, not because it's use is recommended. if you use this, please try to switch to ASM and edit into the original method. ("Edit into" is not "replace." Please keep compatibility with other mods that might be using ASM on the same code.)
	@Deprecated
	Proxy//DO NOT USE THIS -- this is for calls that are generated by the Hook generator directly.
	;
	
	public static final int levels = WrapTiming.values().length;
}
